config/routes.rb
Rails.application.routes.draw do
  

 	root to: "home#index"

  resources :transactions
  resources :accounts
  resources :agencies
  # resources :usuarios

  devise_for :usuarios
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @usuarios = Usuario.all
    @accounts = Account.all    
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @usuarios = Usuario.all
    @accounts = Account.all

  end

  # GET /transactions/1/edit
  def edit
    @usuarios = Usuario.all
    @accounts = Account.all    

  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    account = Account.find(@transaction.accounts_id)
    if account.limite < @transaction.valor
        flash[:error] = "Valor da Transação excede ao limite da conta"
        return redirect_to transactions_path
    end
    
    doneTransaction = account.beginTransaction(@transaction.tipo,@transaction.valor,@transaction.recipient)
    unless doneTransaction
      flash[:error] = account.errors.first
      return redirect_to transactions_path
    end



    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction.rollBack()
    @transaction.destroy
    respond_to do |format|
        format.html { redirect_to transactions_url, notice: 'Transação estornada com sucesso!' }
        format.json { head :no_content }
      end

  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:accounts_id, :valor, :tipo, :usuario_id,:recipient)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%=  simple_form_for @transaction, :html => { :class => "form-horizontal transaction" } do |f| %>

  <% if @transaction.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @transaction.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :accounts_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
       <%= f.collection_select(:accounts_id, @accounts, :id, :conta,{:prompt=>true},{ :class => 'form-control', :required => true }) %>

    </div>
    <%=f.error_span(:accounts_id) %>
  </div>
  <div class="form-group">
    <%= f.label :valor, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.input :valor, as: :decimal, :input_html => { :class => 'form-control', :required => true} , label: false %>
    </div>
    <%=f.error_span(:valor) %>
  </div>
  <div class="form-group">
    <%= f.label :tipo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%=   f.input :tipo,  :as => :select,      :collection => ['Saque','Deposito','Transferência'], :input_html => { :class => 'form-control', :required => true} , label: false %>
    </div>
    <%=f.error_span(:tipo) %>
  </div>
  <div class="form-group">
    <%= f.label :recipient, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
       <%= f.collection_select(:recipient, @accounts, :id, :conta,{:prompt=>"Em caso de transferência selecione aqui a conta de destino"},{ :class => 'form-control'}) %>

    </div>
    <%=f.error_span(:accounts_id) %>
  </div>  
  <div class="form-group">
    <%= f.label :usuario_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
       <%= f.collection_select(:usuario_id, @usuarios, :id, :email,{:prompt=>true},{ :class => 'form-control', :required => true }) %>
    </div>
    <%=f.error_span(:usuario_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                transactions_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/transactions/edit.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/transactions/index.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th>Conta</th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
      <th><%= model_class.human_attribute_name(:tipo) %></th>
      <th>Usuário</th>
      <th>Data da Transação</th>
      <th><%=t '.acoes', :default => "Ações" %></th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= link_to transaction.id, transaction_path(transaction) %></td>
        <td><%= transaction.accounts_id %></td>
        <td><%= transaction.valor %></td>
        <td><%= transaction.tipo %></td>
        <td><%= transaction.usuario_id %></td>
        <td><%=l transaction.created_at %></td>
        <td>
        <%= link_to t('.estornar', :default => "Estonar"),
                      transaction_path(transaction),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Term certeza que deseja estornar essa transação?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_transaction_path,
            :class => 'btn btn-primary' %>

app/views/transactions/new.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/transactions/show.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Conta:</strong></dt>
  <dd><%= @transaction.accounts_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:valor) %>:</strong></dt>
  <dd><%= @transaction.valor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo) %>:</strong></dt>
  <dd><%= @transaction.tipo %></dd>
  <dt><strong>Usuário:</strong></dt>
  <dd><%= @transaction.usuario_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              transactions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_transaction_path(@transaction), :class => 'btn btn-default' %>