config/routes.rb
Rails.application.routes.draw do
  

 	root to: "home#index"

  resources :transactions
  resources :accounts
  resources :agencies
  # resources :usuarios

  devise_for :usuarios
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :agency
  validates :agency_id, presence: true
  validates :conta, presence: true
  validates :limite, presence: true





	def beginTransaction (tipo,valor,recipient)
		
		if tipo == "Deposito"
      self.increment!(:balance,valor)  
    end
    if tipo == "Saque"
     if self.balance.nil? || self.balance < valor 
        self.errors.add("Falha ao Criar Transação", "Saldo Não Disponivel")
        return false
     else   
        self.decrement!(:balance, valor)  
      end 
    end
    if tipo == "Transferência"
     if self.balance.nil? || self.balance < valor 
        self.errors.add("Falha ao Criar Transação", "Saldo Não Disponivel")
        return false
     else   
        destinary = Account.find(recipient)
        self.decrement!(:balance, valor)  
        destinary.increment!(:balance,valor)
        destinary.save
      end 
    end   

   self.save
	end


end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
    @agencies = Agency.all

  end

  # GET /accounts/1/edit
  def edit
    @agencies = Agency.all   
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:agency_id, :conta, :limite)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for @account, :html => { :class => "form-horizontal account" } do |f| %>

  <% if @account.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :agency_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
    <%= f.collection_select(:agency_id, @agencies, :id, :endereco,{:prompt=>true},{ :class => 'form-control', :required => true }) %>
    </div>

    <%=f.error_span(:agency_id) %>
  </div>
  <div class="form-group">
    <%= f.label :conta, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :conta, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:conta) %>
  </div>
  <div class="form-group">
    <%= f.label :limite, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :limite, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:limite) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                accounts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/accounts/edit.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/index.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th>Agência</th>
      <th>Conta</th>
      <th>Limite</th>
      <th>Saldo</th>
      <th><%=t '.acoes', :default => "Ações" %></th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to account.id, account_path(account) %></td>
        <td><%= account.agency_id %></td>
        <td><%= account.conta %></td>
        <td><%= account.limite %></td>
        <td><%= account.balance %></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_account_path(account), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      account_path(account),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_account_path,
            :class => 'btn btn-primary' %>

app/views/accounts/new.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/show.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Agencia:</strong></dt>
  <dd><%= @account.agency_id %></dd>
  <dt><strong>Conta</strong></dt>
  <dd><%= @account.conta %></dd>
  <dt>Limite:</strong></dt>
  <dd><%= @account.limite %></dd>
  <dt><strong>Saldo:</strong></dt>
  <dd><%= @account.balance %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              accounts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_account_path(@account), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              account_path(@account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>